/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backend identity and protocol-version compatibility. */
        get: operations["system_info_v1_system_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Component health rollup. */
        get: operations["system_health_v1_system_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/engines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Engines */
        get: operations["list_engines_v1_engines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/engines/{engine_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Engine Info */
        get: operations["engine_info_v1_engines__engine_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/engines/{engine_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Position */
        post: operations["analyze_position_v1_engines__engine_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analysis/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Position */
        post: operations["analyze_position_v1_analysis_positions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/narration/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Explain Position
         * @description Analyse a position and return grounded coaching narration.
         */
        post: operations["explain_position_v1_narration_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/training/queue/{player}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Queue
         * @description Return up to limit due training cards for player.
         *     When player='default' (no specific player on the Windows host),
         *     aggregate due cards across ALL players.
         */
        get: operations["get_queue_v1_training_queue__player__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/training/review/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Card
         * @description Submit a review rating; update FSRS parameters.
         */
        post: operations["review_card_v1_training_review__card_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/training/seed-from-blunders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seed From Blunders
         * @description Create training cards from blunder positions.
         */
        post: operations["seed_from_blunders_v1_training_seed_from_blunders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/games/{game_id}/eval-graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Eval Graph
         * @description Return per-position evaluation scores for a game, ordered by ply.
         */
        get: operations["get_eval_graph_v1_games__game_id__eval_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/blunders/batch-by-fen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Blunders Batch
         * @description Return blunder classifications for multiple FENs in one round trip.
         */
        post: operations["get_blunders_batch_v1_blunders_batch_by_fen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/blunders/by-fen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Blunders By Fen
         * @description Return blunders matching a specific FEN.
         */
        get: operations["get_blunders_by_fen_v1_blunders_by_fen_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Games
         * @description Return a page of games ordered by creation date descending.
         */
        get: operations["list_games_v1_games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/games/{game_id}/pgn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Game Pgn
         * @description Return the raw PGN for a game.
         */
        get: operations["get_game_pgn_v1_games__game_id__pgn_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repertoire/{player}/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Repertoire Tree */
        get: operations["get_repertoire_tree_v1_repertoire__player__tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repertoire/{player}/gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Repertoire Gaps */
        get: operations["get_repertoire_gaps_v1_repertoire__player__gaps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repertoire/{player}/novelties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Repertoire Novelties */
        get: operations["get_repertoire_novelties_v1_repertoire__player__novelties_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/import/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Pdf
         * @description Ingest a PDF file, detect chess diagrams, and return a summary.
         */
        post: operations["ingest_pdf_v1_import_pdf_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/import/lichess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Lichess
         * @description Fetch games from Lichess and import into the local DB.
         */
        post: operations["import_lichess_v1_import_lichess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repertoire/{player}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Recommendations
         * @description Return engine-backed move suggestions for repertoire gaps.
         */
        post: operations["get_recommendations_v1_repertoire__player__recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/profile/{player}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Profile
         * @description Aggregated statistics for a player.
         */
        get: operations["get_profile_v1_profile__player__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/profile/{player}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Profile Analysis */
        post: operations["get_profile_analysis_v1_profile__player__analysis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/training/schedule/{player}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Training Schedule
         * @description Generate a prioritized multi-day training schedule.
         */
        get: operations["get_training_schedule_v1_training_schedule__player__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisRequest
         * @description Body of ``POST /engines/{engine_id}/analyze``.
         */
        AnalysisRequest: {
            /**
             * Fen
             * @description FEN position to analyze
             * @example rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1
             */
            fen: string;
            /**
             * Depth
             * @description Search depth (plies)
             */
            depth?: number | null;
            /**
             * Nodes
             * @description Search node limit
             */
            nodes?: number | null;
            /**
             * Multipv
             * @description Number of PVs to return
             * @default 1
             */
            multipv: number;
            /**
             * Engine Id
             * @description Engine to use (optional shortcut; normally from URL path)
             */
            engine_id?: string | null;
            /**
             * Options
             * @description Extra UCI options within engine bounds
             */
            options?: {
                [key: string]: string | number | boolean;
            };
            /**
             * Stream
             * @description If true, open engine.<job_id> WS topic
             * @default false
             */
            stream: boolean;
        };
        /** BatchBlunderRequest */
        BatchBlunderRequest: {
            /** Fens */
            fens: string[];
        };
        /** BlunderEnvelope */
        BlunderEnvelope: {
            /** Blunders */
            blunders: components["schemas"]["BlunderOut"][];
        };
        /** BlunderOut */
        BlunderOut: {
            /** Position Id */
            position_id: string;
            /** Fen */
            fen: string;
            /** Game Id */
            game_id: string;
            /** Ply */
            ply: number;
            /** Score Cp */
            score_cp?: number | null;
            /** Classification */
            classification?: string | null;
            /** Cp Delta */
            cp_delta?: number | null;
        };
        /** Body_ingest_pdf_v1_import_pdf_post */
        Body_ingest_pdf_v1_import_pdf_post: {
            /** File */
            file: string;
        };
        /** CardOut */
        CardOut: {
            /** Id */
            id: string;
            /** Card Type */
            card_type: string;
            /** Reference Id */
            reference_id: string;
            /** Fen */
            fen?: string | null;
            /** Move San */
            move_san?: string | null;
            /** Game Id */
            game_id?: string | null;
            /** White */
            white?: string | null;
            /** Black */
            black?: string | null;
            /** Eco */
            eco?: string | null;
            /** Opening */
            opening?: string | null;
            /** Stability */
            stability: number;
            /** Difficulty */
            difficulty: number;
            /** Retrievability */
            retrievability: number;
            /** Reviews */
            reviews: number;
            /** Lapses */
            lapses: number;
            /** Due */
            due: string;
            /** Last Review */
            last_review?: string | null;
        };
        /** DayPlan */
        DayPlan: {
            /** Day */
            day: number;
            /** Date */
            date: string;
            /** Cards */
            cards: components["schemas"]["ScheduledCard"][];
            /** Estimated Minutes */
            estimated_minutes: number;
            /** New Cards */
            new_cards: number;
            /** Review Cards */
            review_cards: number;
            /** Card Type Breakdown */
            card_type_breakdown: {
                [key: string]: number;
            };
        };
        /** EvalPoint */
        EvalPoint: {
            /** Ply */
            ply: number;
            /** Score Cp */
            score_cp?: number | null;
            /** Score Mate */
            score_mate?: number | null;
            /** Move San */
            move_san?: string | null;
            /** Classification */
            classification?: string | null;
        };
        /** GameSummary */
        GameSummary: {
            /** Id */
            id: string;
            /** White */
            white?: string | null;
            /** Black */
            black?: string | null;
            /** Date */
            date?: string | null;
            /** Event */
            event?: string | null;
            /** Result */
            result?: string | null;
            /**
             * Import Status
             * @default pending
             */
            import_status: string;
        };
        /** GamesListResponse */
        GamesListResponse: {
            /** Games */
            games: components["schemas"]["GameSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** GapItem */
        GapItem: {
            /** Fen */
            fen: string;
            /** Ply */
            ply: number;
            /** Move San */
            move_san?: string | null;
            /**
             * Times Reached
             * @default 0
             */
            times_reached: number;
            /**
             * Suggested Alternatives
             * @default []
             */
            suggested_alternatives: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthCheck
         * @description Returned by ``GET /v1/system/health``.
         */
        HealthCheck: {
            /**
             * Status
             * @description Overall rollup of component statuses.
             * @enum {string}
             */
            status: "ok" | "degraded" | "unhealthy";
            /**
             * Components
             * @description Per-component breakdown.
             */
            components?: components["schemas"]["HealthCheckComponent"][];
            /**
             * Uptime Seconds
             * @description Seconds since gateway start.
             */
            uptime_seconds: number;
        };
        /**
         * HealthCheckComponent
         * @description Per-subsystem health entry.
         */
        HealthCheckComponent: {
            /**
             * Name
             * @description Subsystem name, e.g. 'storage', 'engine_orch'.
             */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "unhealthy";
            /**
             * Message
             * @description Optional one-line explanation; absent when status is 'ok'.
             */
            message?: string | null;
        };
        /** LichessImportRequest */
        LichessImportRequest: {
            /** Username */
            username: string;
            /**
             * Max Games
             * @default 50
             */
            max_games: number;
            /** Perf Type */
            perf_type?: string | null;
            /** Rated */
            rated?: boolean | null;
        };
        /** LichessImportResult */
        LichessImportResult: {
            /** Username */
            username: string;
            /** Games Fetched */
            games_fetched: number;
            /** Imported Count */
            imported_count: number;
            /** Errors */
            errors: string[];
        };
        /**
         * NarrationRequest
         * @description Body of POST /v1/narration/explain.
         */
        NarrationRequest: {
            /**
             * Fen
             * @description FEN position to analyse and narrate
             * @example rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1
             */
            fen: string;
            /**
             * Depth
             * @description Engine search depth
             * @default 12
             */
            depth: number;
            /**
             * Engine Id
             * @description Engine id to use
             * @default stockfish
             */
            engine_id: string;
            /**
             * Multipv
             * @description Number of PVs
             * @default 1
             */
            multipv: number;
        };
        /**
         * NarrationResponse
         * @description Response from POST /v1/narration/explain.
         *
         *     Contains the validated narration text and a compact analysis summary
         *     (not the raw AnalysisResult dump — the frontend gets what it needs).
         */
        NarrationResponse: {
            /**
             * Fen
             * @description Position that was analysed
             */
            fen: string;
            /**
             * Narration
             * @description Grounded coaching narration
             */
            narration: string;
            /**
             * Depth Reached
             * @description Max engine depth reached
             */
            depth_reached: number;
            /**
             * Best Move
             * @description Best move in SAN notation
             */
            best_move: string;
            /**
             * Score Display
             * @description Human-readable score, e.g. '+0.38' or 'mate in 2'
             */
            score_display: string;
            /**
             * Pv Moves
             * @description Top PV line moves in SAN
             */
            pv_moves: string[];
        };
        /** NoveltyItem */
        NoveltyItem: {
            /** Fen */
            fen: string;
            /** Ply */
            ply: number;
            /** Move San */
            move_san?: string | null;
            /**
             * Game Id
             * @default
             */
            game_id: string;
            /**
             * Total Times Played
             * @default 0
             */
            total_times_played: number;
        };
        /** OkResponse[HealthCheck] */
        OkResponse_HealthCheck_: {
            data: components["schemas"]["HealthCheck"];
        };
        /** OkResponse[SystemInfo] */
        OkResponse_SystemInfo_: {
            data: components["schemas"]["SystemInfo"];
        };
        /** OpeningNode */
        OpeningNode: {
            /** Fen */
            fen: string;
            /** Move San */
            move_san?: string | null;
            /** Move Uci */
            move_uci?: string | null;
            /**
             * Ply
             * @default 0
             */
            ply: number;
            /**
             * Times Played
             * @default 1
             */
            times_played: number;
            /**
             * Children Count
             * @default 0
             */
            children_count: number;
        };
        /** ProfileAnalysisResponse */
        ProfileAnalysisResponse: {
            /** Player Name */
            player_name: string;
            /** Total Games */
            total_games: number;
            /** Tactical Tendency */
            tactical_tendency: number;
            /** Risk Appetite */
            risk_appetite: number;
            /** Tilt Index */
            tilt_index: number;
            /** Time Pressure Blunders */
            time_pressure_blunders: number;
            /** Opening Breadth */
            opening_breadth: number;
        };
        /** ProfileStats */
        ProfileStats: {
            /** Player Name */
            player_name: string;
            /** Total Games */
            total_games: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Draws */
            draws: number;
            /** Total Analyses */
            total_analyses: number;
            /** Blunder Count */
            blunder_count: number;
            /** Training Cards Due */
            training_cards_due: number;
        };
        /** QueueResponse */
        QueueResponse: {
            /** Due Count */
            due_count: number;
            /** Cards */
            cards: components["schemas"]["CardOut"][];
        };
        /** RecommendationItem */
        RecommendationItem: {
            /** Fen */
            fen: string;
            /** Ply */
            ply: number;
            /**
             * Priority
             * @enum {string}
             */
            priority: "critical" | "important" | "normal";
            /** Best Move Uci */
            best_move_uci: string | null;
            /** Best Move San */
            best_move_san: string | null;
            /** Score Cp */
            score_cp: number | null;
            /** Depth Reached */
            depth_reached: number;
            /** Alternatives Uci */
            alternatives_uci: string[];
            /** Alternatives San */
            alternatives_san: string[];
        };
        /** RecommendationsResponse */
        RecommendationsResponse: {
            /** Player Name */
            player_name: string;
            /** Color */
            color: string;
            /** Total Gaps */
            total_gaps: number;
            /** Recommendations */
            recommendations: components["schemas"]["RecommendationItem"][];
        };
        /** ReviewRequest */
        ReviewRequest: {
            /** Rating */
            rating: number;
        };
        /** ReviewResponse */
        ReviewResponse: {
            /** Id */
            id: string;
            /** New Stability */
            new_stability: number;
            /** New Difficulty */
            new_difficulty: number;
            /** New Retrievability */
            new_retrievability: number;
            /** New Reviews */
            new_reviews: number;
            /** New Due */
            new_due: string;
        };
        /** ScheduledCard */
        ScheduledCard: {
            /** Id */
            id: string;
            /** Card Type */
            card_type: string;
            /** Reference Id */
            reference_id: string;
            /** Stability */
            stability: number;
            /** Difficulty */
            difficulty: number;
            /** Retrievability */
            retrievability: number;
            /** Reviews */
            reviews: number;
            /** Lapses */
            lapses: number;
            /** Due */
            due: string;
            /** Priority Score */
            priority_score: number;
            /** Is New */
            is_new: boolean;
        };
        /** SeedRequest */
        SeedRequest: {
            /**
             * Player
             * @default default
             */
            player: string;
        };
        /**
         * SystemInfo
         * @description Returned by ``GET /v1/system/info``.
         *
         *     Lets a client (typically the GUI) confirm protocol-version compatibility
         *     and discover what the backend can do without poking at every endpoint.
         */
        SystemInfo: {
            /**
             * Backend Version
             * @description Backend semver, e.g. '0.1.0'.
             */
            backend_version: string;
            /**
             * Protocol Min
             * @description Lowest supported protocol version.
             */
            protocol_min: string;
            /**
             * Protocol Max
             * @description Highest supported protocol version.
             */
            protocol_max: string;
            /**
             * Capabilities
             * @description Stable capability flags the client can rely on.
             * @example [
             *       "engine.stockfish",
             *       "narration.grounded"
             *     ]
             */
            capabilities?: string[];
            /**
             * Runtime
             * @description Free-form runtime info (python_version, platform, etc.). Advisory only.
             */
            runtime?: {
                [key: string]: string;
            };
        };
        /** TrainingScheduleResponse */
        TrainingScheduleResponse: {
            /** Player Name */
            player_name: string;
            /** Days */
            days: number;
            /** Daily Minutes */
            daily_minutes: number;
            /** Total Cards Scheduled */
            total_cards_scheduled: number;
            /** Total Due */
            total_due: number;
            /** Schedule */
            schedule: components["schemas"]["DayPlan"][];
        };
        /** TreeResponse */
        TreeResponse: {
            /** Player Name */
            player_name: string;
            /** Color */
            color: string;
            /** Node Count */
            node_count: number;
            /** Nodes */
            nodes: components["schemas"]["OpeningNode"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    system_info_v1_system_info_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse_SystemInfo_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_health_v1_system_health_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse_HealthCheck_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_engines_v1_engines_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    engine_info_v1_engines__engine_id__get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                engine_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_position_v1_engines__engine_id__analyze_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                engine_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_position_v1_analysis_positions_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_position_v1_narration_explain_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NarrationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NarrationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_queue_v1_training_queue__player__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                Authorization?: string | null;
            };
            path: {
                player: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_card_v1_training_review__card_id__post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seed_from_blunders_v1_training_seed_from_blunders_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_eval_graph_v1_games__game_id__eval_graph_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_blunders_batch_v1_blunders_batch_by_fen_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchBlunderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_blunders_by_fen_v1_blunders_by_fen_get: {
        parameters: {
            query: {
                fen: string;
                limit?: number;
            };
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlunderEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_games_v1_games_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GamesListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_pgn_v1_games__game_id__pgn_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repertoire_tree_v1_repertoire__player__tree_get: {
        parameters: {
            query?: {
                color?: string;
            };
            header?: {
                Authorization?: string | null;
            };
            path: {
                player: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repertoire_gaps_v1_repertoire__player__gaps_get: {
        parameters: {
            query?: {
                color?: string;
            };
            header?: {
                Authorization?: string | null;
            };
            path: {
                player: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GapItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repertoire_novelties_v1_repertoire__player__novelties_get: {
        parameters: {
            query?: {
                color?: string;
            };
            header?: {
                Authorization?: string | null;
            };
            path: {
                player: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoveltyItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_pdf_v1_import_pdf_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_pdf_v1_import_pdf_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_lichess_v1_import_lichess_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LichessImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LichessImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recommendations_v1_repertoire__player__recommendations_post: {
        parameters: {
            query?: {
                color?: string;
                limit?: number;
                engine_id?: string;
            };
            header?: {
                Authorization?: string | null;
            };
            path: {
                player: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_v1_profile__player__get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                player: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_analysis_v1_profile__player__analysis_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                player: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_training_schedule_v1_training_schedule__player__get: {
        parameters: {
            query?: {
                days?: number;
                daily_minutes?: number;
            };
            header?: {
                Authorization?: string | null;
            };
            path: {
                player: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingScheduleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
