/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backend identity and protocol-version compatibility. */
        get: operations["system_info_v1_system_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Component health rollup. */
        get: operations["system_health_v1_system_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/engines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Engines */
        get: operations["list_engines_v1_engines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/engines/{engine_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Engine Info */
        get: operations["engine_info_v1_engines__engine_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/engines/{engine_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Position */
        post: operations["analyze_position_v1_engines__engine_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analysis/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Position */
        post: operations["analyze_position_v1_analysis_positions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/narration/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Explain Position
         * @description Generate grounded coaching commentary for a chess position.
         */
        post: operations["explain_position_v1_narration_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/training/queue/{player}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Queue
         * @description Return up to limit due training cards for player.
         *     When player='default' (no specific player on the Windows host),
         *     aggregate due cards across ALL players.
         */
        get: operations["get_queue_v1_training_queue__player__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/training/review/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Card
         * @description Submit a review rating; update FSRS parameters.
         */
        post: operations["review_card_v1_training_review__card_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/training/seed-from-blunders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seed From Blunders
         * @description Create training cards from blunder positions.
         */
        post: operations["seed_from_blunders_v1_training_seed_from_blunders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/games/{game_id}/eval-graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Eval Graph
         * @description Return per-position evaluation scores for a game, ordered by ply.
         *
         *     BBF-22: lazy mode. For each position in the game:
         *       - if an analyses row already exists at the requested depth, return it.
         *       - otherwise, run Stockfish inline, INSERT the result, and return it.
         *
         *     The first call for a new game runs N Stockfish analyses (one per ply).
         *     Subsequent calls are cache hits. With CHESS_COACH_MAX_WORKERS=4 the
         *     first call for a 50-ply game takes ~5s; subsequent calls < 100ms.
         */
        get: operations["get_eval_graph_v1_games__game_id__eval_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/blunders/batch-by-fen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Blunders Batch
         * @description Return blunder classifications for multiple FENs in one round trip.
         */
        post: operations["get_blunders_batch_v1_blunders_batch_by_fen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/blunders/by-fen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Blunders By Fen
         * @description Return blunders matching a specific FEN.
         */
        get: operations["get_blunders_by_fen_v1_blunders_by_fen_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Games
         * @description Return a page of games ordered by creation date descending.
         */
        get: operations["list_games_v1_games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/games/{game_id}/pgn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Game Pgn
         * @description Return the raw PGN for a game.
         */
        get: operations["get_game_pgn_v1_games__game_id__pgn_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repertoire/{player}/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Repertoire Tree */
        get: operations["get_repertoire_tree_v1_repertoire__player__tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repertoire/{player}/gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Repertoire Gaps */
        get: operations["get_repertoire_gaps_v1_repertoire__player__gaps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repertoire/{player}/novelties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Repertoire Novelties */
        get: operations["get_repertoire_novelties_v1_repertoire__player__novelties_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/import/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Pdf
         * @description Extract chess diagrams from a PDF via chessvision.ai.
         */
        post: operations["import_pdf_v1_import_pdf_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/import/lichess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Lichess
         * @description Fetch games from Lichess and import into the local DB.
         */
        post: operations["import_lichess_v1_import_lichess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repertoire/{player}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Recommendations
         * @description Return engine-backed move suggestions for repertoire gaps.
         *
         *     When ``polyglot_book_path`` is supplied, also surface book entries for
         *     the same FENs as additional recommendations tagged ``source="book"``
         *     (or ``"both"`` when the engine already surfaced that UCI). Caller
         *     decides ordering — this route never arbitrates between engine and book.
         */
        post: operations["get_recommendations_v1_repertoire__player__recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/profile/{player}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Profile
         * @description Aggregated statistics for a player.
         */
        get: operations["get_profile_v1_profile__player__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/profile/{player}/explain/{metric_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Explain Metric
         * @description §B4 rule 4: methodology + raw inputs + intermediate values.
         *
         *     Returns the EffectSize result + a full methodology
         *     text + raw inputs + intermediate values for one
         *     metric. The dashboard's "Explain" view links to
         *     this endpoint.
         *
         *     Special case: metric_id == "archetypes" returns the
         *     ArchetypeAssignment (no EffectSize, just a
         *     label + confidence + per-archetype scores).
         */
        get: operations["explain_metric_v1_profile__player__explain__metric_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/profile/{player}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Profile Analysis
         * @description Aggregated Phase 4 metrics for a player.
         *
         *     The response includes both the legacy flat fields
         *     (for backward compat with the pre-BBF-61 dashboard)
         *     AND the new unified `metrics: [{id, value, ...}]` array
         *     (which the BBF-62 dashboard will consume).
         *
         *     The legacy `tilt_index` field is the sequence-based
         *     tilt point_estimate (a re-implementation of the
         *     pre-BBF-54 single-loss-window tilt). When the player
         *     has no qualifying data, the value is 0.0.
         */
        post: operations["get_profile_analysis_v1_profile__player__analysis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/training/schedule/{player}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Training Schedule
         * @description Generate a prioritized multi-day training schedule.
         */
        get: operations["get_training_schedule_v1_training_schedule__player__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Players
         * @description Return all distinct player names from the games table.
         */
        get: operations["list_players_v1_players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kb/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Similar Positions
         * @description Return positions from the KB most similar to the query FEN.
         */
        post: operations["similar_positions_v1_kb_similar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kb/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reindex
         * @description Trigger a reindex of the KB from SQLite. Safe to call multiple times.
         */
        post: operations["reindex_v1_kb_index_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/import/pgn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Pgn
         * @description Parse a PGN string and import each game into the local DB.
         *
         *     BBF-22: this route is now a pure-insert operation. For each game we:
         *       - insert one `games` row (one DB connection, single commit at the end).
         *       - insert one `positions` row per ply (capped by max_plies).
         *
         *     No engine analysis happens here. Analyses are computed lazily by
         *     GET /v1/games/{game_id}/eval-graph on first request and cached in
         *     the `analyses` table.
         *
         *     Import time is O(games * plies) for PGN parsing + DB writes; no
         *     Stockfish is called. A 6000-game PGN imports in seconds, not hours.
         */
        post: operations["import_pgn_v1_import_pgn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/import/backfill-analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Backfill Analyses
         * @description Idempotent: insert missing positions and analyses rows for the given games.
         *
         *     BBF-21: two-phase.
         *       Phase 0: walk every game's PGN (CPU-bound) and check existing
         *                analyses — pure read, no writes, no analysis.
         *       Phase 1: ONE big asyncio.gather() of stockfish analyses across
         *                ALL games' missing plies — the actual bottleneck, fully
         *                parallel across the pool's N slots (BBF-19).
         *       Phase 2: per-game INSERTs of positions then analyses, in small
         *                transactions. Preserves FK ordering (positions.id must
         *                exist before analyses.position_id) and keeps each
         *                transaction small so SQLite write-lock contention stays
         *                low.
         */
        post: operations["backfill_analyses_v1_import_backfill_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/eval/verify/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify Endpoint
         * @description Run the engine against each gold position; return a VerifyResponse.
         *
         *     Response shape (dict; not a Pydantic model — dataclass-to-dict pattern is
         *     faster and the shape is documented here):
         *
         *         {
         *             "corpus_version": "v1" | "v2",
         *             "summary": {
         *                 "total": int,
         *                 "top1_hits": int,
         *                 "top3_hits": int,
         *                 "score_within_50cp": int,
         *                 "mean_delta_cp_abs": float,
         *                 "max_delta_cp_abs": int,
         *             },
         *             "positions": [
         *                 {
         *                     "id": str,
         *                     "fen": str,
         *                     "gold_move_uci": str,
         *                     "gold_score_cp": int,
         *                     "engine_top_move_uci": str,
         *                     "engine_top_score_cp": int,
         *                     "delta_cp": int,
         *                     "status": "match_top1" | "match_topN" | "miss",
         *                 },
         *                 ...
         *             ],
         *         }
         */
        get: operations["verify_endpoint_v1_eval_verify__version__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisRequest
         * @description Body of ``POST /engines/{engine_id}/analyze``.
         */
        AnalysisRequest: {
            /**
             * Fen
             * @description FEN position to analyze
             * @example rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1
             */
            fen: string;
            /**
             * Depth
             * @description Search depth (plies)
             */
            depth?: number | null;
            /**
             * Nodes
             * @description Search node limit
             */
            nodes?: number | null;
            /**
             * Multipv
             * @description Number of PVs to return
             * @default 1
             */
            multipv: number;
            /**
             * Engine Id
             * @description Engine to use (optional shortcut; normally from URL path)
             */
            engine_id?: string | null;
            /**
             * Options
             * @description Extra UCI options within engine bounds
             */
            options?: {
                [key: string]: string | number | boolean;
            };
            /**
             * Stream
             * @description If true, open engine.<job_id> WS topic
             * @default false
             */
            stream: boolean;
        };
        /** BackfillRequest */
        BackfillRequest: {
            /**
             * Game Ids
             * @description If empty, back-fill all games with pgn_raw populated
             */
            game_ids?: string[];
            /**
             * Depth
             * @default 8
             */
            depth: number;
            /**
             * Max Plies
             * @default 200
             */
            max_plies: number;
        };
        /** BackfillResponse */
        BackfillResponse: {
            /** Games Processed */
            games_processed: number;
            /** Games Skipped No Pgn */
            games_skipped_no_pgn: number;
            /** Plies Analyzed */
            plies_analyzed: number;
            /** Plies Skipped Existing */
            plies_skipped_existing: number;
            /** Positions Inserted */
            positions_inserted: number;
            /** Failures */
            failures: number;
        };
        /** BatchBlunderRequest */
        BatchBlunderRequest: {
            /** Fens */
            fens: string[];
        };
        /** BlunderEnvelope */
        BlunderEnvelope: {
            /** Blunders */
            blunders: components["schemas"]["BlunderOut"][];
        };
        /** BlunderOut */
        BlunderOut: {
            /** Position Id */
            position_id: string;
            /** Fen */
            fen: string;
            /** Game Id */
            game_id: string;
            /** Ply */
            ply: number;
            /** Score Cp */
            score_cp?: number | null;
            /** Classification */
            classification?: string | null;
            /** Cp Delta */
            cp_delta?: number | null;
        };
        /** Body_import_pdf_v1_import_pdf_post */
        Body_import_pdf_v1_import_pdf_post: {
            /** File */
            file: string;
        };
        /** CardOut */
        CardOut: {
            /** Id */
            id: string;
            /** Card Type */
            card_type: string;
            /** Reference Id */
            reference_id: string;
            /** Fen */
            fen?: string | null;
            /** Move San */
            move_san?: string | null;
            /** Game Id */
            game_id?: string | null;
            /** White */
            white?: string | null;
            /** Black */
            black?: string | null;
            /** Eco */
            eco?: string | null;
            /** Opening */
            opening?: string | null;
            /** Stability */
            stability: number;
            /** Difficulty */
            difficulty: number;
            /** Retrievability */
            retrievability: number;
            /** Reviews */
            reviews: number;
            /** Lapses */
            lapses: number;
            /** Due */
            due: string;
            /** Last Review */
            last_review?: string | null;
        };
        /**
         * CorpusVersion
         * @description L-2 corpus versions supported by the verifier.
         * @enum {string}
         */
        CorpusVersion: "v1" | "v2";
        /** DayPlan */
        DayPlan: {
            /** Day */
            day: number;
            /** Date */
            date: string;
            /** Cards */
            cards: components["schemas"]["ScheduledCard"][];
            /** Estimated Minutes */
            estimated_minutes: number;
            /** New Cards */
            new_cards: number;
            /** Review Cards */
            review_cards: number;
            /** Card Type Breakdown */
            card_type_breakdown: {
                [key: string]: number;
            };
        };
        /** DiagramResult */
        DiagramResult: {
            /** Page */
            page: number;
            /**
             * Diagram Index
             * @description 0-based index of this diagram within the page. The public chessvision.ai /predict endpoint returns at most one FEN per page, so the route always emits 0 for valid responses. A future multi-board backend (or a local page-segmentation model) would emit 0, 1, 2, ... in reading order.
             * @default 0
             */
            diagram_index: number;
            /** Fen */
            fen: string | null;
            /** Valid */
            valid: boolean;
            /** Confidence */
            confidence: number;
            /** Issue */
            issue?: string | null;
        };
        /** EvalPoint */
        EvalPoint: {
            /** Ply */
            ply: number;
            /** Score Cp */
            score_cp?: number | null;
            /** Score Mate */
            score_mate?: number | null;
            /** Move San */
            move_san?: string | null;
            /** Classification */
            classification?: string | null;
        };
        /** GameSummary */
        GameSummary: {
            /** Id */
            id: string;
            /** White */
            white?: string | null;
            /** Black */
            black?: string | null;
            /** Date */
            date?: string | null;
            /** Event */
            event?: string | null;
            /** Result */
            result?: string | null;
            /**
             * Import Status
             * @default pending
             */
            import_status: string;
        };
        /** GamesListResponse */
        GamesListResponse: {
            /** Games */
            games: components["schemas"]["GameSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** GapItem */
        GapItem: {
            /** Fen */
            fen: string;
            /** Ply */
            ply: number;
            /** Move San */
            move_san?: string | null;
            /**
             * Times Reached
             * @default 0
             */
            times_reached: number;
            /**
             * Suggested Alternatives
             * @default []
             */
            suggested_alternatives: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthCheck
         * @description Returned by ``GET /v1/system/health``.
         */
        HealthCheck: {
            /**
             * Status
             * @description Overall rollup of component statuses.
             * @enum {string}
             */
            status: "ok" | "degraded" | "unhealthy";
            /**
             * Components
             * @description Per-component breakdown.
             */
            components?: components["schemas"]["HealthCheckComponent"][];
            /**
             * Uptime Seconds
             * @description Seconds since gateway start.
             */
            uptime_seconds: number;
        };
        /**
         * HealthCheckComponent
         * @description Per-subsystem health entry.
         */
        HealthCheckComponent: {
            /**
             * Name
             * @description Subsystem name, e.g. 'storage', 'engine_orch'.
             */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "unhealthy";
            /**
             * Message
             * @description Optional one-line explanation; absent when status is 'ok'.
             */
            message?: string | null;
        };
        /** ImportedGame */
        ImportedGame: {
            /** Game Id */
            game_id: string;
            /** White */
            white: string | null;
            /** Black */
            black: string | null;
            /** Result */
            result: string | null;
            /** Event */
            event: string | null;
            /** Date */
            date: string | null;
        };
        /** IndexRequest */
        IndexRequest: {
            /**
             * Limit
             * @description Max positions to index
             * @default 5000
             */
            limit: number;
        };
        /** LichessImportRequest */
        LichessImportRequest: {
            /** Username */
            username: string;
            /**
             * Max Games
             * @default 50
             */
            max_games: number;
            /** Perf Type */
            perf_type?: string | null;
            /** Rated */
            rated?: boolean | null;
        };
        /** LichessImportResult */
        LichessImportResult: {
            /** Username */
            username: string;
            /** Games Fetched */
            games_fetched: number;
            /** Imported Count */
            imported_count: number;
            /** Errors */
            errors: string[];
        };
        /**
         * MetricExplainResponse
         * @description §B4 rule 4: methodology + raw inputs + intermediate values.
         *
         *     Fields:
         *       player_name: The player this explanation is for.
         *       metric_id: The metric name (e.g.
         *           "tactical_vs_positional_bias"). One of the 6
         *           metrics + "archetypes" + "sequence_based_tilt".
         *       effect: The EffectSize result from running the
         *           metric. shape: (point_estimate, d, ci_low,
         *           ci_high, sample_size, null_value). For the
         *           archetype clusterer, this carries the
         *           confidence in [0, 1] (not a per-metric
         *           EffectSize).
         *       passes_b4_gate: True iff gate_metric() returns
         *           True. For the archetype clusterer, this is
         *           True iff confidence > 0.4.
         *       methodology: The full text of the metric's
         *           methodology section (from
         *           docs/15_methodology/profile-metrics-v1.md).
         *       raw_inputs: A dict of the raw inputs to the
         *           metric (player name, db path, SQL filter
         *           parameters). The keys are metric-specific.
         *       intermediate_values: A dict of intermediate
         *           values computed during the metric's run
         *           (e.g. for tactical_vs_positional_bias:
         *           {'opportunities': 50, 'taken': 31, 'rate': 0.62}).
         *       caveats: A list of strings describing caveats
         *           (e.g. "Sample size is below the §B4
         *           threshold; the metric's point estimate is
         *           not surfaced as a coaching insight").
         */
        MetricExplainResponse: {
            /** Player Name */
            player_name: string;
            /** Metric Id */
            metric_id: string;
            /** Effect */
            effect: {
                [key: string]: unknown;
            };
            /** Passes B4 Gate */
            passes_b4_gate: boolean;
            /** Methodology */
            methodology: string;
            /** Raw Inputs */
            raw_inputs: {
                [key: string]: unknown;
            };
            /** Intermediate Values */
            intermediate_values: {
                [key: string]: unknown;
            };
            /** Caveats */
            caveats?: string[];
        };
        /**
         * NarrationRequest
         * @description Body of POST /v1/narration/explain.
         *
         *     Supports two consumption modes:
         *       1. Simple narration (no engine call): the route accepts pre-computed
         *          context (move_san, eval_cp, game_phase, player_name, context) and
         *          skips engine invocation. depth/engine_id/multipv are ignored.
         *       2. Engine-backed narration (future Phase 3 endpoint): depth,
         *          engine_id, multipv drive a real engine analysis before narration.
         *
         *     All optional fields default to None so the type remains compatible
         *     with both modes and with clients that only know the simple contract.
         */
        NarrationRequest: {
            /**
             * Fen
             * @description FEN position to analyse and narrate
             * @example rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1
             */
            fen: string;
            /**
             * Move San
             * @description Move just played in SAN, if known (e.g. 'Nf6', 'e4').
             */
            move_san?: string | null;
            /**
             * Eval Cp
             * @description Pre-computed evaluation in centipawns (positive = white).
             */
            eval_cp?: number | null;
            /**
             * Game Phase
             * @description One of "opening", "middlegame", "endgame".
             */
            game_phase?: string | null;
            /**
             * Player Name
             * @description Optional player name for personalised narration.
             */
            player_name?: string | null;
            /**
             * Context
             * @description Free-form extra context appended to the narration prompt.
             */
            context?: string | null;
            /**
             * Depth
             * @description Engine search depth. None = use endpoint default (12).
             */
            depth?: number | null;
            /**
             * Engine Id
             * @description Engine id to use. None = use endpoint default ('stockfish').
             */
            engine_id?: string | null;
            /**
             * Multipv
             * @description Number of PVs. None = use endpoint default (1).
             */
            multipv?: number | null;
        };
        /**
         * NarrationRouteResponse
         * @description Route-layer response wrapper.
         *
         *     Embeds the canonical NarrationResponse fields plus route-local audit
         *     metadata (narration_id, grounded, created_at). The audit fields are
         *     useful to clients -- the grounded flag drives frontend commentary
         *     rendering (ungrounded/template outputs render with a different style).
         */
        NarrationRouteResponse: {
            /**
             * Fen
             * @description Position that was analysed
             */
            fen: string;
            /**
             * Narration
             * @description Grounded coaching narration
             */
            narration: string;
            /**
             * Depth Reached
             * @description Max engine depth reached. Populated only when narration is engine-backed; None for template/LLM-only paths.
             */
            depth_reached?: number | null;
            /**
             * Best Move
             * @description Best move in UCI notation (e.g. 'e2e4'). Populated only when narration is engine-backed; None for template/LLM-only paths.
             */
            best_move?: string | null;
            /**
             * Score Display
             * @description Human-readable score, e.g. '+0.38' or 'mate in 2'
             */
            score_display: string;
            /**
             * Pv Moves
             * @description Top PV line moves in UCI notation (e.g. ["e2e4", "e7e5"])
             */
            pv_moves: string[];
            /**
             * Pv Moves San
             * @description Top PV line moves in SAN notation (e.g. ["e4", "e5", "Nf3"]), human-display-only. Authoritative on the wire is pv_moves (UCI); SAN here is never authoritative (specs/v1.0/chess-coach-protocol-v1.md:42). Length matches pv_moves 1:1.
             */
            pv_moves_san?: string[];
            /**
             * Corpus Entry Id
             * @description The v2 narrative corpus entry (NG-v2-NNNN) whose narrative_explanation grounded this narration. None when no FEN match in the corpus.
             */
            corpus_entry_id?: string | null;
            /** Narration Id */
            narration_id: string;
            /** Grounded */
            grounded: boolean;
            /** Created At */
            created_at: string;
        };
        /** NoveltyItem */
        NoveltyItem: {
            /** Fen */
            fen: string;
            /** Ply */
            ply: number;
            /** Move San */
            move_san?: string | null;
            /**
             * Game Id
             * @default
             */
            game_id: string;
            /**
             * Total Times Played
             * @default 0
             */
            total_times_played: number;
        };
        /** OkResponse[HealthCheck] */
        OkResponse_HealthCheck_: {
            data: components["schemas"]["HealthCheck"];
        };
        /** OkResponse[SystemInfo] */
        OkResponse_SystemInfo_: {
            data: components["schemas"]["SystemInfo"];
        };
        /** OpeningNode */
        OpeningNode: {
            /** Fen */
            fen: string;
            /** Move San */
            move_san?: string | null;
            /** Move Uci */
            move_uci?: string | null;
            /**
             * Ply
             * @default 0
             */
            ply: number;
            /**
             * Times Played
             * @default 1
             */
            times_played: number;
            /**
             * Children Count
             * @default 0
             */
            children_count: number;
        };
        /** PdfImportResponse */
        PdfImportResponse: {
            /** Import Id */
            import_id: string;
            /** Filename */
            filename: string;
            /** Pages Processed */
            pages_processed: number;
            /** Diagrams Found */
            diagrams_found: number;
            /** Diagrams Valid */
            diagrams_valid: number;
            /**
             * Max Diagrams Per Page
             * @description Upper bound on the number of DiagramResult entries produced from a single PDF page. The public chessvision.ai /predict endpoint emits at most one FEN per page, so this constant is 1 today. A future multi-board backend (or local page-segmentation model) would raise this bound.
             * @default 1
             */
            max_diagrams_per_page: number;
            /**
             * Diagrams
             * @description One DiagramResult per OCR'd page. With the chessvision default backend, at most one DiagramResult is produced per page (max_diagrams_per_page=1). Pages where the OCR backend returned success=false emit a DiagramResult with fen=None and a populated issue field; they do not produce a FEN.
             */
            diagrams: components["schemas"]["DiagramResult"][];
        };
        /** PgnImportRequest */
        PgnImportRequest: {
            /**
             * Pgn
             * @description PGN text, single or multi-game
             */
            pgn: string;
            /**
             * Depth
             * @description Depth used by future lazy analyses at GET /v1/games/{id}/eval-graph
             * @default 8
             */
            depth: number;
            /**
             * Max Games
             * @default 500
             */
            max_games: number;
            /**
             * Max Plies
             * @description Cap on positions stored per game
             * @default 200
             */
            max_plies: number;
        };
        /** PgnImportResponse */
        PgnImportResponse: {
            /** Import Id */
            import_id: string;
            /** Imported Count */
            imported_count: number;
            /** Failed Count */
            failed_count: number;
            /** Total Games */
            total_games: number;
            /** Positions Count */
            positions_count: number;
            /** Analyzed Count */
            analyzed_count: number;
            /** Analysis Failed Count */
            analysis_failed_count: number;
            /** Results */
            results: components["schemas"]["ImportedGame"][];
        };
        /** PlayerListResponse */
        PlayerListResponse: {
            /** Players */
            players: string[];
        };
        /**
         * ProfileAnalysisResponse
         * @description Unified Phase 4 response shape.
         *
         *     The flat legacy fields are kept for backward compat
         *     with the pre-BBF-61 dashboard. New clients should
         *     read from `metrics: [{id, value, ...}]`.
         */
        ProfileAnalysisResponse: {
            /** Player Name */
            player_name: string;
            /** Total Games */
            total_games: number;
            /** Tactical Tendency */
            tactical_tendency: number;
            /** Risk Appetite */
            risk_appetite: number;
            /** Tilt Index */
            tilt_index: number;
            /** Time Pressure Blunders */
            time_pressure_blunders: number;
            /** Opening Breadth */
            opening_breadth: number;
            /** Metrics */
            metrics?: components["schemas"]["ProfileMetric"][];
        };
        /**
         * ProfileMetric
         * @description One metric in the response. Per §B4, carries enough
         *     metadata for the UI to decide whether to surface as a
         *     coaching insight.
         */
        ProfileMetric: {
            /** Id */
            id: string;
            /** Value */
            value: number | null;
            /** Sample Size */
            sample_size: number;
            /** D */
            d: number | null;
            /** Ci Low */
            ci_low?: number | null;
            /** Ci High */
            ci_high?: number | null;
            /** Passes B4 Gate */
            passes_b4_gate: boolean;
        };
        /** ProfileStats */
        ProfileStats: {
            /** Player Name */
            player_name: string;
            /** Total Games */
            total_games: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Draws */
            draws: number;
            /** Total Analyses */
            total_analyses: number;
            /** Blunder Count */
            blunder_count: number;
            /** Training Cards Due */
            training_cards_due: number;
        };
        /** QueueResponse */
        QueueResponse: {
            /** Due Count */
            due_count: number;
            /** Cards */
            cards: components["schemas"]["CardOut"][];
        };
        /** RecommendationItem */
        RecommendationItem: {
            /** Fen */
            fen: string;
            /** Ply */
            ply: number;
            /**
             * Priority
             * @enum {string}
             */
            priority: "critical" | "important" | "normal";
            /** Best Move Uci */
            best_move_uci: string | null;
            /** Best Move San */
            best_move_san: string | null;
            /** Score Cp */
            score_cp: number | null;
            /** Depth Reached */
            depth_reached: number;
            /** Alternatives Uci */
            alternatives_uci: string[];
            /** Alternatives San */
            alternatives_san: string[];
            /**
             * Source
             * @default engine
             * @enum {string}
             */
            source: "engine" | "book" | "both";
            /** Book Weight */
            book_weight?: number | null;
        };
        /** RecommendationsResponse */
        RecommendationsResponse: {
            /** Player Name */
            player_name: string;
            /** Color */
            color: string;
            /** Total Gaps */
            total_gaps: number;
            /** Recommendations */
            recommendations: components["schemas"]["RecommendationItem"][];
        };
        /** ReviewRequest */
        ReviewRequest: {
            /** Rating */
            rating: number;
        };
        /** ReviewResponse */
        ReviewResponse: {
            /** Id */
            id: string;
            /** New Stability */
            new_stability: number;
            /** New Difficulty */
            new_difficulty: number;
            /** New Retrievability */
            new_retrievability: number;
            /** New Reviews */
            new_reviews: number;
            /** New Due */
            new_due: string;
        };
        /** ScheduledCard */
        ScheduledCard: {
            /** Id */
            id: string;
            /** Card Type */
            card_type: string;
            /** Reference Id */
            reference_id: string;
            /** Stability */
            stability: number;
            /** Difficulty */
            difficulty: number;
            /** Retrievability */
            retrievability: number;
            /** Reviews */
            reviews: number;
            /** Lapses */
            lapses: number;
            /** Due */
            due: string;
            /** Priority Score */
            priority_score: number;
            /** Is New */
            is_new: boolean;
        };
        /** SeedRequest */
        SeedRequest: {
            /**
             * Player
             * @default default
             */
            player: string;
        };
        /** SimilarHit */
        SimilarHit: {
            /**
             * Rank
             * @description Result rank (1 = most similar)
             */
            rank: number;
            /** Fen */
            fen: string;
            /** Ply */
            ply: number;
            /** Game Id */
            game_id: string;
        };
        /** SimilarRequest */
        SimilarRequest: {
            /**
             * Fen
             * @description Query FEN to find similar positions for
             */
            fen: string;
            /**
             * Top K
             * @description Number of results to return
             * @default 5
             */
            top_k: number;
        };
        /** SimilarResponse */
        SimilarResponse: {
            /** Query Fen */
            query_fen: string;
            /** Hits */
            hits: components["schemas"]["SimilarHit"][];
            /**
             * Kb Ready
             * @description False if the KB store has not been indexed yet — hits will be empty
             */
            kb_ready: boolean;
        };
        /**
         * SystemInfo
         * @description Returned by ``GET /v1/system/info``.
         *
         *     Lets a client (typically the GUI) confirm protocol-version compatibility
         *     and discover what the backend can do without poking at every endpoint.
         */
        SystemInfo: {
            /**
             * Backend Version
             * @description Backend semver, e.g. '0.1.0'.
             */
            backend_version: string;
            /**
             * Protocol Min
             * @description Lowest supported protocol version.
             */
            protocol_min: string;
            /**
             * Protocol Max
             * @description Highest supported protocol version.
             */
            protocol_max: string;
            /**
             * Capabilities
             * @description Stable capability flags the client can rely on.
             * @example [
             *       "engine.stockfish",
             *       "narration.grounded"
             *     ]
             */
            capabilities?: string[];
            /**
             * Runtime
             * @description Free-form runtime info (python_version, platform, etc.). Advisory only.
             */
            runtime?: {
                [key: string]: string;
            };
        };
        /** TrainingScheduleResponse */
        TrainingScheduleResponse: {
            /** Player Name */
            player_name: string;
            /** Days */
            days: number;
            /** Daily Minutes */
            daily_minutes: number;
            /** Total Cards Scheduled */
            total_cards_scheduled: number;
            /** Total Due */
            total_due: number;
            /** Schedule */
            schedule: components["schemas"]["DayPlan"][];
        };
        /** TreeResponse */
        TreeResponse: {
            /** Player Name */
            player_name: string;
            /** Color */
            color: string;
            /** Node Count */
            node_count: number;
            /** Nodes */
            nodes: components["schemas"]["OpeningNode"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    system_info_v1_system_info_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse_SystemInfo_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_health_v1_system_health_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse_HealthCheck_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_engines_v1_engines_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    engine_info_v1_engines__engine_id__get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                engine_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_position_v1_engines__engine_id__analyze_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                engine_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_position_v1_analysis_positions_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_position_v1_narration_explain_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NarrationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NarrationRouteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_queue_v1_training_queue__player__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                Authorization?: string | null;
            };
            path: {
                player: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_card_v1_training_review__card_id__post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seed_from_blunders_v1_training_seed_from_blunders_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_eval_graph_v1_games__game_id__eval_graph_get: {
        parameters: {
            query?: {
                depth?: number;
            };
            header?: {
                Authorization?: string | null;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_blunders_batch_v1_blunders_batch_by_fen_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchBlunderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_blunders_by_fen_v1_blunders_by_fen_get: {
        parameters: {
            query: {
                fen: string;
                limit?: number;
            };
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlunderEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_games_v1_games_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GamesListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_pgn_v1_games__game_id__pgn_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repertoire_tree_v1_repertoire__player__tree_get: {
        parameters: {
            query?: {
                color?: string;
            };
            header?: {
                Authorization?: string | null;
            };
            path: {
                player: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repertoire_gaps_v1_repertoire__player__gaps_get: {
        parameters: {
            query?: {
                color?: string;
            };
            header?: {
                Authorization?: string | null;
            };
            path: {
                player: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GapItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repertoire_novelties_v1_repertoire__player__novelties_get: {
        parameters: {
            query?: {
                color?: string;
            };
            header?: {
                Authorization?: string | null;
            };
            path: {
                player: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoveltyItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_pdf_v1_import_pdf_post: {
        parameters: {
            query?: {
                max_pages?: number;
            };
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_pdf_v1_import_pdf_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PdfImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_lichess_v1_import_lichess_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LichessImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LichessImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recommendations_v1_repertoire__player__recommendations_post: {
        parameters: {
            query?: {
                color?: string;
                limit?: number;
                engine_id?: string;
                /** @description Optional path to a Polyglot .bin opening book. When provided, book entries for each gap FEN are surfaced alongside engine PVs (per FU-7 blending (iv): per-move union, no arbitration). Caller decides precedence. Per-call only — not persisted. */
                polyglot_book_path?: string | null;
            };
            header?: {
                Authorization?: string | null;
            };
            path: {
                player: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_v1_profile__player__get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                player: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_metric_v1_profile__player__explain__metric_id__get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                player: string;
                metric_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricExplainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_analysis_v1_profile__player__analysis_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                player: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_training_schedule_v1_training_schedule__player__get: {
        parameters: {
            query?: {
                days?: number;
                daily_minutes?: number;
            };
            header?: {
                Authorization?: string | null;
            };
            path: {
                player: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingScheduleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_players_v1_players_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    similar_positions_v1_kb_similar_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimilarRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reindex_v1_kb_index_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndexRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_pgn_v1_import_pgn_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PgnImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PgnImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backfill_analyses_v1_import_backfill_analyses_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BackfillRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackfillResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_endpoint_v1_eval_verify__version__get: {
        parameters: {
            query?: {
                depth?: number;
                top_n?: number;
            };
            header?: {
                Authorization?: string | null;
            };
            path: {
                version: components["schemas"]["CorpusVersion"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
