/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RepertoireRouteImport } from './routes/repertoire'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PdfRouteImport } from './routes/pdf'
import { Route as LichessRouteImport } from './routes/lichess'
import { Route as GamesRouteImport } from './routes/games'
import { Route as FilesRouteImport } from './routes/files'
import { Route as EnginesRouteImport } from './routes/engines'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatabasesIndexRouteImport } from './routes/databases/index'
import { Route as GamesGameIdRouteImport } from './routes/games.$gameId'
import { Route as DatabasesDatabaseIdRouteImport } from './routes/databases/$databaseId'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RepertoireRoute = RepertoireRouteImport.update({
  id: '/repertoire',
  path: '/repertoire',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfRoute = PdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const LichessRoute = LichessRouteImport.update({
  id: '/lichess',
  path: '/lichess',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const EnginesRoute = EnginesRouteImport.update({
  id: '/engines',
  path: '/engines',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabasesIndexRoute = DatabasesIndexRouteImport.update({
  id: '/databases/',
  path: '/databases/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => GamesRoute,
} as any)
const DatabasesDatabaseIdRoute = DatabasesDatabaseIdRouteImport.update({
  id: '/databases/$databaseId',
  path: '/databases/$databaseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/coach': typeof CoachRoute
  '/engines': typeof EnginesRoute
  '/files': typeof FilesRoute
  '/games': typeof GamesRouteWithChildren
  '/lichess': typeof LichessRoute
  '/pdf': typeof PdfRoute
  '/profile': typeof ProfileRoute
  '/repertoire': typeof RepertoireRoute
  '/settings': typeof SettingsRoute
  '/training': typeof TrainingRoute
  '/databases/$databaseId': typeof DatabasesDatabaseIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/databases/': typeof DatabasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/coach': typeof CoachRoute
  '/engines': typeof EnginesRoute
  '/files': typeof FilesRoute
  '/games': typeof GamesRouteWithChildren
  '/lichess': typeof LichessRoute
  '/pdf': typeof PdfRoute
  '/profile': typeof ProfileRoute
  '/repertoire': typeof RepertoireRoute
  '/settings': typeof SettingsRoute
  '/training': typeof TrainingRoute
  '/databases/$databaseId': typeof DatabasesDatabaseIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/databases': typeof DatabasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/coach': typeof CoachRoute
  '/engines': typeof EnginesRoute
  '/files': typeof FilesRoute
  '/games': typeof GamesRouteWithChildren
  '/lichess': typeof LichessRoute
  '/pdf': typeof PdfRoute
  '/profile': typeof ProfileRoute
  '/repertoire': typeof RepertoireRoute
  '/settings': typeof SettingsRoute
  '/training': typeof TrainingRoute
  '/databases/$databaseId': typeof DatabasesDatabaseIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/databases/': typeof DatabasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/coach'
    | '/engines'
    | '/files'
    | '/games'
    | '/lichess'
    | '/pdf'
    | '/profile'
    | '/repertoire'
    | '/settings'
    | '/training'
    | '/databases/$databaseId'
    | '/games/$gameId'
    | '/databases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/coach'
    | '/engines'
    | '/files'
    | '/games'
    | '/lichess'
    | '/pdf'
    | '/profile'
    | '/repertoire'
    | '/settings'
    | '/training'
    | '/databases/$databaseId'
    | '/games/$gameId'
    | '/databases'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/coach'
    | '/engines'
    | '/files'
    | '/games'
    | '/lichess'
    | '/pdf'
    | '/profile'
    | '/repertoire'
    | '/settings'
    | '/training'
    | '/databases/$databaseId'
    | '/games/$gameId'
    | '/databases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  CoachRoute: typeof CoachRoute
  EnginesRoute: typeof EnginesRoute
  FilesRoute: typeof FilesRoute
  GamesRoute: typeof GamesRouteWithChildren
  LichessRoute: typeof LichessRoute
  PdfRoute: typeof PdfRoute
  ProfileRoute: typeof ProfileRoute
  RepertoireRoute: typeof RepertoireRoute
  SettingsRoute: typeof SettingsRoute
  TrainingRoute: typeof TrainingRoute
  DatabasesDatabaseIdRoute: typeof DatabasesDatabaseIdRoute
  DatabasesIndexRoute: typeof DatabasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repertoire': {
      id: '/repertoire'
      path: '/repertoire'
      fullPath: '/repertoire'
      preLoaderRoute: typeof RepertoireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf': {
      id: '/pdf'
      path: '/pdf'
      fullPath: '/pdf'
      preLoaderRoute: typeof PdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lichess': {
      id: '/lichess'
      path: '/lichess'
      fullPath: '/lichess'
      preLoaderRoute: typeof LichessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engines': {
      id: '/engines'
      path: '/engines'
      fullPath: '/engines'
      preLoaderRoute: typeof EnginesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/databases/': {
      id: '/databases/'
      path: '/databases'
      fullPath: '/databases/'
      preLoaderRoute: typeof DatabasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof GamesRoute
    }
    '/databases/$databaseId': {
      id: '/databases/$databaseId'
      path: '/databases/$databaseId'
      fullPath: '/databases/$databaseId'
      preLoaderRoute: typeof DatabasesDatabaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GamesRouteChildren {
  GamesGameIdRoute: typeof GamesGameIdRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesGameIdRoute: GamesGameIdRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  CoachRoute: CoachRoute,
  EnginesRoute: EnginesRoute,
  FilesRoute: FilesRoute,
  GamesRoute: GamesRouteWithChildren,
  LichessRoute: LichessRoute,
  PdfRoute: PdfRoute,
  ProfileRoute: ProfileRoute,
  RepertoireRoute: RepertoireRoute,
  SettingsRoute: SettingsRoute,
  TrainingRoute: TrainingRoute,
  DatabasesDatabaseIdRoute: DatabasesDatabaseIdRoute,
  DatabasesIndexRoute: DatabasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
